//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerSocialNet.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string Text { get; set; }
        public int LikesCounter { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual LikeComment LikeComment { get; set; }
        public virtual Post Post { get; set; }
        public virtual SocialUser Author { get; set; }
    }
}
