//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerSocialNet.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend : SocialUser
    {
        public int FriendId { get; set; }
    
        public virtual SocialUser UserFriend { get; set; }
    }
}
